---

## Server & Database Settings ##

server             : none   # none|apache|nginx|h2o|litespeed
fastcgi            : none   # none|php-fpm
database           : none   # none|mysql|mariadb

db_root_password   : admin

## Programming languages Settings ##
# If the version is set to 0, the programming language does not install
python_version     : 3.12.2      # 3.12.2
ruby_version       : 3.2.2       # 3.2.2
php_version        : 8.2.19      # 8.2.19
perl_version       : 5.38.0      # 5.38.0
node_version       : 14.21.3     # 14.21.3
go_version         : 1.15.6      # 1.15.6
java_version       : 17          # 17 # 11 or 17 LTS
scala_version      : 2.11.12     # 2.11.12 (require java)

## Develop & Deploy Settings ##

ssl                : true    # true|false
docker             : false   # true|false
phpmyadmin         : false   # true|false (require PHP and database)

## That's all, stop setting. Let's vagrant up!! ##
