---
- name: git checkout jenv
  ansible.builtin.git:
    repo: https://github.com/gcuisinier/jenv.git
    dest: "{{ jenv_dir }}"
    version: "master"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH jenv on .bashrc_alias
  ansible.builtin.lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "export PATH=$HOME/.jenv/bin:$PATH"
    mode: "0644"

- name: edit jenv init on .bashrc_alias
  ansible.builtin.lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "eval \"$(jenv init -)\""
    mode: "0644"

- name: java added via jenv (CentOS/RHEL)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.command: sudo -u vagrant -i -- jenv add /usr/lib/jvm/jre-{{ java_version | default(17) }}.0

- name: java added via jenv (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.command: sudo -u vagrant -i -- jenv add /usr/lib/jvm/java-{{ java_version | default(17) }}-openjdk-amd64

- name: stat jenv
  ansible.builtin.stat:
    path: "{{ jenv_dir }}/bin/jenv"
  register: is_jenv

- name: exists is_jenv
  when: is_jenv.stat.exists
  block:
  - name: jenv global
    ansible.builtin.command: "{{ jenv_dir }}/bin/jenv global {{ java_version | default(1.8) }}"
    become: yes
    become_user: vagrant

  - name: jenv rehash
    ansible.builtin.command: "{{ jenv_dir }}/bin/jenv rehash"
    become: yes
    become_user: vagrant
