---
- name: git checkout jenv
  git:
    repo: https://github.com/gcuisinier/jenv.git
    dest: "{{ home_dir }}/.jenv"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH jenv on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "export PATH=$HOME/.jenv/bin:$PATH"

- name: edit jenv init on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "eval \"$(jenv init -)\""

- name: java added via jenv (CentOS/RHEL)
  command: sudo -u vagrant -i -- jenv add /usr/lib/jvm/jre-{{ java_version | default(1.8) }}.0
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: java added via jenv (Debian)
  command: sudo -u vagrant -i -- jenv add /usr/lib/jvm/java-{{ java_version | default(1.8) }}.0-openjdk-amd64
  when: ansible_os_family == 'Debian'
  ignore_errors: yes
  
- name: jenv global
  shell: ~/.jenv/bin/jenv global {{ java_version | default(1.8) }}
  become: yes
  become_user: vagrant

- name: jenv rehash
  shell: ~/.jenv/bin/jenv rehash
  become: yes
  become_user: vagrant
