---
- name: git checkout jenv
  git: repo=https://github.com/gcuisinier/jenv.git dest={{ home_dir }}/.jenv force=yes
  become: yes

- name: change mode, owner and group
  file: dest={{ home_dir }}/.jenv state=directory mode=0755 recurse=yes owner=vagrant group=vagrant
  become: yes

- name: edit PATH jenv on .bash_profile
  lineinfile: dest={{ home_dir }}/.bash_profile line="export PATH=$HOME/.jenv/bin:$PATH"

- name: edit PATH jenv on .bashrc
  lineinfile: dest={{ home_dir }}/.bashrc line="export PATH=$HOME/.jenv/bin:$PATH"

- name: edit jenv init on .bash_profile
  lineinfile: dest={{ home_dir }}/.bash_profile line="eval \"$(jenv init -)\""

- name: edit jenv init on .bashrc
  lineinfile: dest={{ home_dir }}/.bashrc line="eval \"$(jenv init -)\""

- name: java added via jenv
  command: sudo -u vagrant -i -- jenv add /usr/lib/jvm/jre-{{ java_version | default(1.8) }}.0
  ignore_errors: yes

- name: jenv global
  command: sudo -u vagrant -i -- jenv global {{ java_version | default(1.8) }}

- name: jenv rehash
  command: sudo -u vagrant -i -- jenv rehash
