---
- name: nginx repository installed (CentOS/RHEL 6)
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6

- name: nginx repository installed (CentOS/RHEL 7)
  yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7

- name: nginx installed
  package: name=nginx

- name: stat custom nginx.conf.j2
  stat: path=/vagrant/config/nginx.conf.j2
  register: is_custom_nginx_conf

- name: custom nginx.conf changed
  template: src=/vagrant/config/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  when: is_custom_nginx_conf.stat.exists

- name: nginx.conf changed
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  when: not is_custom_nginx_conf.stat.exists

- name: change user form nginx to www-data
  replace: dest=/etc/nginx/nginx.conf regexp='user              nginx;' replace="user              www-data;"
  when: ansible_os_family == 'Debian'

- name: stat custom nginx.www.conf.j2
  stat: path=/vagrant/config/nginx.www.conf.j2
  register: is_custom_www_conf

- name: custom nginx.conf changed
  template: src=/vagrant/config/nginx.www.conf.j2 dest=/etc/nginx/conf.d/www.conf
  when: is_custom_www_conf.stat.exists

- name: www.conf changed
  template: src=nginx.www.conf.j2 dest=/etc/nginx/conf.d/www.conf
  when: not is_custom_www_conf.stat.exists

- name: nginx started and enabled
  service: name=nginx state=restarted enabled=yes
