---
- name: Development Tools installed
  package:
    name: "@Development Tools"
    state: present

- name: libraries installed
  package:
    name:
      - yum-utils
      - python-pip
      - libcurl
      - libcurl-devel
      - jq
    state: latest
