---
- name: git checkout plenv
  git:
    repo: https://github.com/tokuhirom/plenv.git
    dest: "{{ home_dir }}/.plenv"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH plenv on .bash_profile
  lineinfile:
    dest: "{{ home_dir }}/.bash_profile"
    line: "export PATH=$HOME/.plenv/bin:$PATH"

- name: edit PATH plenv on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "export PATH=$HOME/.plenv/bin:$PATH"

- name: edit plenv init on .bash_profile
  lineinfile:
    dest: "{{ home_dir }}/.bash_profile"
    line: "eval \"$(plenv init -)\""

- name: edit plenv init on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "eval \"$(plenv init -)\""

- name: git checkout perl-build
  git:
    repo: https://github.com/tokuhirom/Perl-Build.git
    dest: "{{ home_dir }}/.plenv/plugins/perl-build"
    force: yes
  become: yes
  become_user: vagrant

- name: stat perl_path
  stat:
    path: "{{ home_dir }}/.plenv/versions/{{ perl_version | default(5.25.1) }}"
  register: is_perl_path

- name: perl installed via plenv
  command: sudo -u vagrant -i -- plenv install {{ perl_version | default(5.25.1) }}
  when: not is_perl_path.stat.exists

- name: plenv rehash
  command: sudo -u vagrant -i -- plenv rehash

- name: plenv global
  command: sudo -u vagrant -i -- plenv global {{ perl_version | default(5.25.1) }}

- name: cpanm module installed
  command: sudo -u vagrant -i -- plenv install-cpanm

- name: Carton module installed
  command: sudo -u vagrant -i -- cpanm Carton

- name: Server::Starter module installed
  command: sudo -u vagrant -i -- cpanm Server::Starter
