---
- name: git checkout plenv
  git: repo=https://github.com/tokuhirom/plenv.git dest=/home/vagrant/.plenv force=yes
  become: yes

- name: change mode, owner and group
  file: dest=/home/vagrant/.plenv state=directory mode=0755 recurse=yes owner=vagrant group=vagrant
  become: yes

- name: edit PATH plenv on .bash_profile
  lineinfile: dest={{ bash_profile }} line="export PATH=$HOME/.plenv/bin:$PATH"

- name: edit PATH plenv on .bashrc
  lineinfile: dest={{ bashrc }} line="export PATH=$HOME/.plenv/bin:$PATH"

- name: edit plenv init on .bash_profile
  lineinfile: dest={{ bash_profile }} line="eval \"$(plenv init -)\""

- name: edit plenv init on .bashrc
  lineinfile: dest={{ bashrc }} line="eval \"$(plenv init -)\""

- name: git checkout perl-build
  git: repo=https://github.com/tokuhirom/Perl-Build.git dest=/home/vagrant/.plenv/plugins/perl-build force=yes
  become: yes

- name: stat perl_path
  stat: path=/home/vagrant/.plenv/versions/{{ perl_version | default(5.25.1) }}
  register: is_perl_path

- name: perl installed by plenv
  command: sudo -u vagrant -i -- plenv install {{ perl_version | default(5.25.1) }}
  when: not is_perl_path.stat.exists

- command: sudo -u vagrant -i -- plenv rehash
- command: sudo -u vagrant -i -- plenv global {{ perl_version | default(5.25.1) }}

- name: cpanm module installed
  command: sudo -u vagrant -i -- plenv install-cpanm

- name: Carton module installed
  command: sudo -u vagrant -i -- cpanm Carton
