---
- name: git checkout plenv
  git:
    repo: https://github.com/tokuhirom/plenv.git
    dest: "{{ plenv_dir }}"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH plenv on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "export PATH=$HOME/.plenv/bin:$PATH"

- name: edit plenv init on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "eval \"$(plenv init -)\""

- name: git checkout perl-build
  git:
    repo: https://github.com/tokuhirom/Perl-Build.git
    dest: "{{ plenv_dir }}/plugins/perl-build"
    force: yes
  become: yes
  become_user: vagrant

- name: stat perl_path
  stat:
    path: "{{ plenv_dir }}/versions/{{ perl_version | default(5.26.1) }}"
  register: is_perl_path

- name: perl installed via plenv
  command: "{{ plenv_dir }}/bin/plenv install {{ perl_version | default(5.26.1) }}"
  become: yes
  become_user: vagrant
  when: not is_perl_path.stat.exists

- name: plenv global
  command: "{{ plenv_dir }}/bin/plenv global {{ perl_version | default(5.26.1) }}"
  become: yes
  become_user: vagrant

- name: plenv rehash
  command: "{{ plenv_dir }}/bin/plenv rehash"
  become: yes
  become_user: vagrant

- name: cpanm module installed
  command: "{{ plenv_dir }}/bin/plenv install-cpanm"
  become: yes
  become_user: vagrant

- name: Carton module installed
  command: "{{ plenv_dir }}/shims/cpanm Carton"
  become: yes
  become_user: vagrant

- name: Server::Starter module installed
  command: "{{ plenv_dir }}/shims/cpanm Server::Starter"
  become: yes
  become_user: vagrant
