---
- name: git checkout plenv
  git:
    repo: https://github.com/tokuhirom/plenv.git
    dest: "{{ plenv_dir }}"
    version: "master"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH plenv on .bashrc_alias
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "export PATH=$HOME/.plenv/bin:$PATH"
    mode: 0644

- name: edit plenv init on .bashrc_alias
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "eval \"$(plenv init -)\""
    mode: 0644

- name: git checkout perl-build
  git:
    repo: https://github.com/tokuhirom/Perl-Build.git
    dest: "{{ plenv_dir }}/plugins/perl-build"
    version: "master"
    force: yes
  become: yes
  become_user: vagrant

- name: stat plenv
  stat:
    path: "{{ plenv_dir }}/bin/plenv"
  register: is_plenv

- name: exists is_plenv
  block:
  - name: perl installed via plenv
    command: "{{ plenv_dir }}/bin/plenv install {{ perl_version | default(5.32.0) }}"
    become: yes
    become_user: vagrant
    register: plenv_result
    failed_when:
      - plenv_result.rc != 0
      - plenv_result.rc != 255

  - name: plenv global
    command: "{{ plenv_dir }}/bin/plenv global {{ perl_version | default(5.32.0) }}"
    become: yes
    become_user: vagrant

  - name: plenv rehash
    command: "{{ plenv_dir }}/bin/plenv rehash"
    become: yes
    become_user: vagrant

  - name: cpanm module installed
    command: "{{ plenv_dir }}/bin/plenv install-cpanm"
    become: yes
    become_user: vagrant
  when: is_plenv.stat.exists

- name: stat cpanm
  stat:
    path: "{{ plenv_dir }}/bin/cpm"
  register: is_cpm

- name: not exists is_cpm
  block:
  - name: cpm module installed
    shell: curl -fsSL --compressed https://git.io/cpm > "{{ plenv_dir }}/bin/cpm"

  - name: chmod 755
    file:
      path: "{{ plenv_dir }}/bin/cpm"
      mode: 0755
  when: not is_cpm.stat.exists

- name: stat cpanm
  stat:
    path: "{{ plenv_dir }}/shims/cpanm"
  register: is_cpanm

- name: exists is_cpanm
  block:
  - name: Carton module installed
    command: "{{ plenv_dir }}/shims/cpanm Carton"
    become: yes
    become_user: vagrant

  - name: Server::Starter module installed
    command: "{{ plenv_dir }}/shims/cpanm Server::Starter"
    become: yes
    become_user: vagrant

  - name: App::UpdateCPANfile module installed
    command: "{{ plenv_dir }}/shims/cpanm App::UpdateCPANfile"
    become: yes
    become_user: vagrant
  when: is_cpanm.stat.exists
