---
- name: litespeed repository installed (CentOS/RHEL 6)
  yum:
    name: http://rpms.litespeedtech.com/centos/litespeed-repo-1.1-1.el6.noarch.rpm
  when: ansible_distribution_major_version|int == 6

- name: litespeed repository installed (CentOS/RHEL 7)
  yum:
    name: http://rpms.litespeedtech.com/centos/litespeed-repo-1.1-1.el7.noarch.rpm
  when: ansible_distribution_major_version|int == 7

- name: litespeed installed
  package:
    name: openlitespeed
    state: latest

- name: lsws enabled
  service:
    name: lsws
    enabled: yes
  notify: lsws restarted
