---
- name: OpenJDK 9 installed
  package:
    name: openjdk-9-jdk
    state: latest
  when: java_version == 1.9

- block:
  - name: ppa:openjdk-r/ppa repository installed
    apt_repository:
      repo: "ppa:openjdk-r/ppa"
      state: present

  - name: OpenJDK 8 installed (Ubuntu)
    package:
      name: openjdk-8-jdk
      state: latest
  when:
    - java_version == 1.8
    - ansible_distribution == 'Ubuntu'

- block:
  - name: OpenJDK 8 installed (Debian buster or stretch)
    apt:
      name: openjdk-8-jdk
      state: latest
    when: ansible_distribution_release == 'buster' or ansible_distribution_release == 'stretch'

  - name: OpenJDK 8 installed (Debian jessie)
    apt:
      name: openjdk-8-jdk
      state: latest
      default_release: jessie-backports
    when:
      - ansible_distribution_release == 'jessie'
  when:
    - java_version == 1.8
    - ansible_distribution == 'Debian'

- name: OpenJDK 7 installed
  package:
    name: openjdk-7-jdk
    state: latest
  when: java_version == 1.7
