---
- name: OpenJDK 11 installed
  package:
    name: openjdk-11-jdk
    state: latest
  when: java_version is version('11', '==')

- name: OpenJDK 17 installed
  package:
    name: openjdk-17-jdk
    state: latest
  when: java_version is version('17', '==')
