---
- name: OpenJDK 11 installed
  when: java_version is version('11', '==')
  ansible.builtin.package:
    name: openjdk-11-jdk
    state: latest

- name: OpenJDK 17 installed
  when: java_version is version('17', '==')
  ansible.builtin.package:
    name: openjdk-17-jdk
    state: latest
