---
- name: OpenJDK 8 installed
  when: java_version is version('1.8', '==')
  ansible.builtin.package:
    name: java-1.8.0-openjdk
    state: latest

- name: OpenJDK 7 installed
  when: java_version is version('1.7', '==')
  ansible.builtin.package:
    name: java-1.7.0-openjdk
    state: latest

- name: OpenJDK 6 installed
  when: java_version is version('1.6', '==')
  ansible.builtin.package:
    name: java-1.6.0-openjdk
    state: latest
