---
- name: stat phpMyAdmin_path
  stat:
    path: "{{ DOCUMENT_ROOT }}/phpMyAdmin"
  register: is_phpMyAdmin_path

- block:
  - name: phpMyAdmin download
    get_url:
      url: "{{ phpMyAdmin_zip_url }}"
      dest: "/tmp/phpMyAdmin.zip"
      validate_certs: no

  - name: unzip phpMyAdmin.zip
    command: unzip -o /tmp/phpMyAdmin.zip -d /tmp

  - name: mv phpMyAdmin.zip
    command: mv /tmp/{{ phpMyAdmin_dir }} {{ DOCUMENT_ROOT }}/phpMyAdmin

  - name: delete phpMyAdmin.zip
    file:
      path: "/tmp/phpMyAdmin.zip"
      state: absent
  when: not is_phpMyAdmin_path.stat.exists

- name: stat phpMyAdmin_config
  stat:
    path: "{{ DOCUMENT_ROOT }}/phpMyAdmin/config.inc.php"
  register: is_phpMyAdmin_config

- name: mv config.inc.php
  command: mv {{ DOCUMENT_ROOT }}/phpMyAdmin/config.sample.inc.php {{ DOCUMENT_ROOT }}/phpMyAdmin/config.inc.php
  when: not is_phpMyAdmin_config.stat.exists

- name: edit config.inc.php
  replace:
    dest: "{{ DOCUMENT_ROOT }}/phpMyAdmin/config.inc.php"
    regexp: "blowfish_secret'] = '';"
    replace: "blowfish_secret'] = 'E=L(LSpfv9Z5R70)JuCe$Lu#^thWI9xc2-)FziBA1N=';"

- name: edit config.inc.php
  replace:
    dest: "{{ DOCUMENT_ROOT }}/phpMyAdmin/config.inc.php"
    regexp: "host'] = 'localhost';"
    replace: "host'] = '127.0.0.1';"
