---
- name: stat phpMyAdmin_path
  stat:
    path: "{{ DOCUMENT_ROOT }}/phpMyAdmin"
  register: is_phpMyAdmin_path

- name: phpMyAdmin download
  get_url:
    url: "{{ phpMyAdmin_url }}"
    dest: "{{ DOCUMENT_ROOT }}/phpMyAdmin.zip"
    validate_certs: no
  when: not is_phpMyAdmin_path.stat.exists

- name: unzip phpMyAdmin.zip
  unarchive:
    src: "{{ DOCUMENT_ROOT }}/phpMyAdmin.zip"
    dest: "{{ DOCUMENT_ROOT }}"
  when: not is_phpMyAdmin_path.stat.exists

- name: delete phpMyAdmin.zip
  file:
    path: "{{ DOCUMENT_ROOT }}/phpMyAdmin.zip"
    state: absent

- name: stat phpMyAdmin_config
  stat:
    path: "{{ DOCUMENT_ROOT }}/phpMyAdmin/config.inc.php"
  register: is_phpMyAdmin_config

- name: mv config.inc.php
  command: mv {{ DOCUMENT_ROOT }}/phpMyAdmin/config.sample.inc.php {{ DOCUMENT_ROOT }}/phpMyAdmin/config.inc.php
  when: not is_phpMyAdmin_config.stat.exists

- name: edit config.inc.php
  replace:
    dest: "{{ DOCUMENT_ROOT }}/phpMyAdmin/config.inc.php"
    regexp: "^$cfg['blowfish_secret'] = '';"
    replace: "$cfg['blowfish_secret'] = 'E=L(LSpfv9Z5R70)JuCe$Lu#^thWI9xc2-)FziBA1N=';"

- name: edit config.inc.php
  replace:
    dest: "{{ DOCUMENT_ROOT }}/phpMyAdmin/config.inc.php"
    regexp: "^$cfg['Servers'][$i]['host'] = 'localhost';"
    replace: "$cfg['Servers'][$i]['host'] = '127.0.0.1';"
