---
- block:
  - name: MariaDB 10.1 repository added (CentOS/RHEL 6)
    yum_repository:
      name: mariadb
      description: MariaDB 10.1 centos repository
      baseurl: http://yum.mariadb.org/10.1/centos6-amd64
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: yes

  - name: MariaDB installed (CentOS/RHEL 6)
    package: name={{ item }} state=latest
    with_items:
      - MariaDB-server
      - MariaDB-client
      - MariaDB-common
      - MariaDB-compat
      - MariaDB-devel
      - MariaDB-shared
      - MySQL-python
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 6

- block:
  - name: MariaDB 10.1 repository installed (CentOS/RHEL 7)
    yum_repository:
      name: mariadb
      description: MariaDB 10.1 centos repository
      baseurl: http://yum.mariadb.org/10.1/centos7-amd64
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: yes

  - name: MariaDB 10.1 installed (CentOS/RHEL 7)
    package: name={{ item }} state=latest
    with_items:
      - mariadb-server
      - MariaDB-client
      - mariadb
      - mariadb-devel
      - mariadb-libs
      - mariadb-embedded
      - MySQL-python
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7

- block:
  - name: MariaDB apt_key installed (Ubuntu/xenial)
    apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8
    when: ansible_distribution_release == 'xenial'

  - name: MariaDB apt_key installed (Ubuntu/trusty or precise)
    apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
    when: ansible_distribution_release == 'trusty' or ansible_distribution_release == 'precise'

  - name: MariaDB 10.1 repository installed
    apt_repository: filename='MariaDB' repo='deb [arch=amd64,i386,ppc64el] http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/repo/10.1/ubuntu {{ ansible_distribution_release }} main'

  - name: MariaDB 10.1 installed (Ubuntu)
    package: name={{ item }} state=latest
    with_items:
      - mariadb-server
      - libmariadbd-dev
      - python-mysqldb
  when: ansible_distribution == 'Ubuntu'

- block:
  - name: MariaDB 10.1 apt_key installed (Debian)
    apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

  - name: MariaDB 10.1 repository installed
    apt_repository: filename='MariaDB' repo='deb [arch=amd64,i386] http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/repo/10.1/debian {{ ansible_distribution_release }} main'

  - name: MariaDB 10.1 installed (Debian)
    package: name={{ item }} state=latest
    with_items:
      - mariadb-server
      - libmariadbd-dev
      - python-mysqldb
  when: ansible_distribution == 'Debian'

- name: stat custom my.cnf.j2
  stat: path=/vagrant/config/my.cnf.j2
  register: is_custom_my_conf

- name: custom my.cnf changed
  template: src=/vagrant/config/my.cnf.j2 dest=/etc/my.cnf
  when: is_custom_my_conf.stat.exists

- name: my.cnf changed
  template: src=my.cnf.j2 dest=/etc/my.cnf
  when: not is_custom_my_conf.stat.exists

- name: mysqld started and enabled
  service: name=mysql state=restarted enabled=yes

- name: set MariaDB root password
  mysql_user:
    name: "root"
    password: "{{ db_root_password }}"
    host: "localhost"
    state: present
  ignore_errors: yes

- name: set MariaDB root password
  mysql_user:
    name: "root"
    password: "{{ db_root_password }}"
    host: "{{ item }}"
    state: present
    login_user: "root"
    login_password: "{{ db_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: Delete blank MariaDB users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
    login_user: "root"
    login_password: "{{ db_root_password }}"
  with_items:
    - localhost

- name: Drop MariaDB test database
  mysql_db:
    name: test
    state: absent
    login_user: "root"
    login_password: "{{ db_root_password }}"
