---
- name: mysql repository installed (CentOS/RHEL 6)
  yum: name=https://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6

- name: mysql repository installed (CentOS/RHEL 7)
  yum: name=https://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7

- name: mysql installed
  yum: name={{ item }} state=latest
  with_items:
    - mysql-community-server
    - mysql-community-devel
    - mysql-community-client
    - mysql-community-common
    - mysql-community-libs
    - mysql-utilities
    - MySQL-python

- name: stat custom my.cnf.j2
  stat: path=/vagrant/config/my.cnf.j2
  register: is_custom_my_conf

- name: custom my.cnf changed
  template: src=/vagrant/config/my.cnf.j2 dest=/etc/my.cnf
  when: is_custom_my_conf.stat.exists

- name: my.cnf changed
  template: src=my.cnf.j2 dest=/etc/my.cnf
  when: not is_custom_my_conf.stat.exists

- name: mysqld started and enabled
  service: name=mysqld state=restarted enabled=yes

- name: set mysql root password
  mysql_user:
    name: "root"
    password: "{{ db_root_password }}"
    host: "localhost"
    state: present
  ignore_errors: yes

- name: set mysql root password
  mysql_user:
    name: "root"
    password: "{{ db_root_password }}"
    host: "{{ item }}"
    state: present
    login_user: "root"
    login_password: "{{ db_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: Delete blank MySQL users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
    login_user: "root"
    login_password: "{{ db_root_password }}"
  with_items:
    - localhost

- name: Drop MySQL test database
  mysql_db:
     name: test
     state: absent
     login_user: "root"
     login_password: "{{ db_root_password }}"

- name: create symbolic link
  file: src=/var/lib/mysql/mysql.sock dest=/tmp/mysql.sock state=link
