---
- block:
  - name: percona repository installed (CentOS/RHEL)
    yum:
      name: http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm

  - name: percona 5.7 installed (CentOS/RHEL)
    package:
      name:
        - Percona-Server-server-57
        - Percona-Server-client-57
        - Percona-Server-shared-57
        - Percona-Server-devel-57
      state: latest

  - name: python-PyMySQL installed (CentOS/RHEL 7 or 6)
    package:
      name:
        - MySQL-python
      state: latest
    when: ansible_distribution_major_version|int == 6 or ansible_distribution_major_version|int == 7

  - name: python-PyMySQL installed (CentOS/RHEL 8)
    package:
      name:
        - python3-PyMySQL
      state: latest
    when: ansible_distribution_major_version|int == 8

  when: ansible_os_family == 'RedHat'

- block:
  - name: percona-release repository installed (Debian)
    apt:
      deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"

  - name: apt-get update
    apt:
      update_cache: yes

  - name: percona 5.7 installed (Debian)
    package:
      name:
        - percona-server-server-5.7
        - percona-server-client-5.7
        - percona-server-common-5.7
        - libperconaserverclient20-dev
        - python-mysqldb
      state: latest
  when: ansible_os_family == 'Debian'
