---
- name: git checkout scalaenv
  git:
    repo: https://github.com/mazgi/scalaenv.git
    dest: "{{ scalaenv_dir }}"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH scalaenv on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "export PATH=$HOME/.scalaenv/bin:$PATH"

- name: edit scalaenv init on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "eval \"$(scalaenv init -)\""

- name: Scala installed via scalaenv
  command: "{{ scalaenv_dir }}/bin/scalaenv install scala-{{ scala_version | default(2.11.12) }}"
  ignore_errors: yes
  become: yes
  become_user: vagrant

- name: scalaenv global
  command: "{{ scalaenv_dir }}/bin/scalaenv global scala-{{ scala_version | default(2.11.12) }}"
  become: yes
  become_user: vagrant

- name: scalaenv rehash
  command: "{{ scalaenv_dir }}/bin/scalaenv rehash"
  become: yes
  become_user: vagrant
