---
- name: git checkout scalaenv
  git:
    repo: https://github.com/mazgi/scalaenv.git
    dest: "{{ home_dir }}/.scalaenv"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH scalaenv on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "export PATH=$HOME/.scalaenv/bin:$PATH"

- name: edit scalaenv init on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "eval \"$(scalaenv init -)\""

- name: Scala installed via scalaenv
  command: ~/.scalaenv/bin/scalaenv install scala-{{ scala_version | default(2.11.8) }}
  ignore_errors: yes
  become: yes
  become_user: vagrant

- name: ~/.scalaenv/bin/scalaenv global
  command: ~/.scalaenv/bin/scalaenv global scala-{{ scala_version | default(2.11.8) }}
  become: yes
  become_user: vagrant

- name: scalaenv rehash
  command: ~/.scalaenv/bin/scalaenv rehash
  become: yes
  become_user: vagrant
