---
- name: git checkout scalaenv
  git:
    repo: https://github.com/mazgi/scalaenv.git
    dest: "{{ scalaenv_dir }}"
    version: "master"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH scalaenv on .bashrc_alias
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "export PATH=$HOME/.scalaenv/bin:$PATH"
    mode: 0644

- name: edit scalaenv init on .bashrc_alias
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "eval \"$(scalaenv init -)\""
    mode: 0644

- name: stat scalaenv
  stat:
    path: "{{ scalaenv_dir }}/bin/scalaenv"
  register: is_scalaenv

- name: exists is_scalaenv
  block:
  - name: Scala installed via scalaenv
    command: "{{ scalaenv_dir }}/bin/scalaenv install scala-{{ scala_version | default(2.11.12) }}"
    become: yes
    become_user: vagrant
    register: scalaenv_result
    failed_when:
      - scalaenv_result.rc != 0
      - scalaenv_result.rc != 1

  - name: scalaenv global
    command: "{{ scalaenv_dir }}/bin/scalaenv global scala-{{ scala_version | default(2.11.12) }}"
    become: yes
    become_user: vagrant

  - name: scalaenv rehash
    command: "{{ scalaenv_dir }}/bin/scalaenv rehash"
    become: yes
    become_user: vagrant
  when: is_scalaenv.stat.exists
