---
- name: git checkout goenv
  git:
    repo: https://github.com/wfarr/goenv.git
    dest: "{{ goenv_dir }}"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH goenv on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "export PATH=$HOME/.goenv/bin:$PATH"

- name: edit goenv init on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "eval \"$(goenv init -)\""

- name: Go installed via goenv
  command: "{{ goenv_dir }}/bin/goenv install {{ go_version | default(1.15.6) }}"
  ignore_errors: yes
  become: yes
  become_user: vagrant

- name: goenv global
  command: "{{ goenv_dir }}/bin/goenv global {{ go_version | default(1.15.6) }}"
  become: yes
  become_user: vagrant

- name: goenv rehash
  command: "{{ goenv_dir }}/bin/goenv rehash"
  become: yes
  become_user: vagrant
