---
- name: git checkout goenv
  git:
    repo: https://github.com/wfarr/goenv.git
    dest: "{{ home_dir }}/.goenv"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH goenv on .bash_profile
  lineinfile:
    dest: "{{ home_dir }}/.bash_profile"
    line: "export PATH=$HOME/.goenv/bin:$PATH"

- name: edit PATH goenv on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "export PATH=$HOME/.goenv/bin:$PATH"

- name: edit goenv init on .bash_profile
  lineinfile:
    dest: "{{ home_dir }}/.bash_profile"
    line: "eval \"$(goenv init -)\""

- name: edit goenv init on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "eval \"$(goenv init -)\""

- name: Go installed via goenv
  command: ~/.goenv/bin/goenv install {{ go_version | default(1.6.3) }}
  ignore_errors: yes
  become: yes
  become_user: vagrant

- name: goenv global
  command: ~/.goenv/bin/goenv global {{ go_version | default(1.6.3) }}
  become: yes
  become_user: vagrant

- name: goenv rehash
  command: ~/.goenv/bin/goenv rehash
  become: yes
  become_user: vagrant
