---
- name: git checkout pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ pyenv_dir }}"
    version: "master"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PYENV_ROOT on .bashrc_alias
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "export PYENV_ROOT=\"$HOME/.pyenv\""
    mode: 0644

- name: edit PATH pyenv on .bashrc_alias
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "export PATH=$HOME/.pyenv/bin:$PATH"
    mode: 0644

- name: edit pyenv init on .bashrc_alias
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "eval \"$(pyenv init --path)\""
    mode: 0644

- name: git checkout pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ pyenv_dir }}/plugins/pyenv-virtualenv"
    version: "master"
    force: yes
  become: yes
  become_user: vagrant

- name: edit virtualenv-init init on .bashrc_alias
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_alias"
    line: "eval \"$(pyenv virtualenv-init -)\""
    mode: 0644

- include_tasks: build-env.yml

- name: stat pyenv
  stat:
    path: "{{ pyenv_dir }}/bin/pyenv"
  register: is_pyenv

- name: exists is_pyenv
  block:
  - name: Python installed via pyenv
    command: "{{ pyenv_dir }}/bin/pyenv install {{ python_version | default(3.9.2) }}"
    become: yes
    become_user: vagrant
    register: pyenv_result
    failed_when:
      - pyenv_result.rc != 0
      - pyenv_result.rc != 1

  - name: pyenv global
    command: "{{ pyenv_dir }}/bin/pyenv global {{ python_version | default(3.9.2) }}"
    become: yes
    become_user: vagrant

  - name: pyenv rehash
    command: "{{ pyenv_dir }}/bin/pyenv rehash"
    become: yes
    become_user: vagrant
  when: is_pyenv.stat.exists
