---
- name: git checkout pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ home_dir }}/.pyenv"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH pyenv on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "export PATH=$HOME/.pyenv/bin:$PATH"

- name: edit pyenv init on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "eval \"$(pyenv init -)\""

- name: git checkout pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ home_dir }}/.pyenv/plugins/pyenv-virtualenv"
    force: yes
  become: yes
  become_user: vagrant

- name: edit virtualenv-init init on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "eval \"$(pyenv virtualenv-init -)\""

- include: build-env.yml

- name: Python installed via pyenv
  command: ~/.pyenv/bin/pyenv install {{ python_version | default(3.5.1) }}
#  ignore_errors: yes
  failed_when: false
  become: yes
  become_user: vagrant

- name: pyenv global
  command: ~/.pyenv/bin/pyenv global {{ python_version | default(3.5.1) }}
  become: yes
  become_user: vagrant

- name: pyenv rehash
  command: ~/.pyenv/bin/pyenv rehash
  become: yes
  become_user: vagrant
