---
- name: git checkout pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ pyenv_dir }}"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH pyenv on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "export PATH=$HOME/.pyenv/bin:$PATH"

- name: edit pyenv init on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "eval \"$(pyenv init -)\""

- name: git checkout pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ pyenv_dir }}/plugins/pyenv-virtualenv"
    force: yes
  become: yes
  become_user: vagrant

- name: edit virtualenv-init init on .bashrc_vap
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vap"
    line: "eval \"$(pyenv virtualenv-init -)\""

- include: build-env.yml

- name: Python installed via pyenv
  command: "{{ pyenv_dir }}/bin/pyenv install {{ python_version | default(3.9.2) }}"
  ignore_errors: yes
  become: yes
  become_user: vagrant

- name: pyenv global
  command: "{{ pyenv_dir }}/bin/pyenv global {{ python_version | default(3.9.2) }}"
  become: yes
  become_user: vagrant

- name: pyenv rehash
  command: "{{ pyenv_dir }}/bin/pyenv rehash"
  become: yes
  become_user: vagrant
