---
- name: sysv-rc-conf installed
  package:
    name: sysv-rc-conf
    state: latest
  when: ansible_distribution_release == 'trusty'

- name: apt-transport-https installed
  package:
    name: apt-transport-https
    state: latest
  when: ansible_distribution == 'Debian'
