---
- name: service facts
  service_facts:

# - name: print service facts
#   debug:
#     var: ansible_facts.services

- name: apache stopped
  service:
    name: httpd
    state: stopped
    enabled: no
  when:
    - server != 'apache'
    - item.key == 'httpd.service'
    - item.value.state == 'running'
  with_dict: "{{ ansible_facts.services }}"

- name: apache2 stopped
  service:
    name: apache2
    state: stopped
    enabled: no
  when:
    - server != 'apache'
    - item.key == 'apache2.service'
    - item.value.state == 'running'
  with_dict: "{{ ansible_facts.services }}"

- name: nginx stopped
  service:
    name: nginx
    state: stopped
    enabled: no
  when:
    - server != 'nginx'
    - item.key == 'nginx.service'
    - item.value.state == 'running'
  with_dict: "{{ ansible_facts.services }}"

- name: h2o stopped
  service:
    name: h2o
    state: stopped
    enabled: no
  when:
    - server != 'h2o'
    - item.key == 'h2o.service'
    - item.value.state == 'running'
  with_dict: "{{ ansible_facts.services }}"

- name: php-fpm stopped
  service:
    name: php-fpm
    state: stopped
    enabled: no
  when:
    - fastcgi != 'php-fpm'
    - item.key == 'php-fpm.service'
    - item.value.state == 'running'
  with_dict: "{{ ansible_facts.services }}"

- name: mysql
  block:
  - name: removed mysql
    package:
      name: mysql*
      state: absent
    when:
      - item.key == 'mysql.service'
      - item.value.state == 'running'
    with_dict: "{{ ansible_facts.services }}"

  - name: removed mysql
    package:
      name: mysql*
      state: absent
    when:
      - item.key == 'mysqld.service'
      - item.value.state == 'running'
    with_dict: "{{ ansible_facts.services }}"
  when:
    - database != 'mysql'

- name: MariaDB
  block:
  - name: removed MariaDB
    package:
      name: MariaDB*
      state: absent
    when:
      - ansible_os_family == 'RedHat'
      - item.key == 'mariadb.service'
      - item.value.state == 'running'
    with_dict: "{{ ansible_facts.services }}"

  - name: removed mariadb
    package:
      name: mariadb*
      state: absent
    when:
      - item.key == 'mariadb.service'
      - item.value.state == 'running'
    with_dict: "{{ ansible_facts.services }}"

  - name: delete symbolic links
    file:
      path: /etc/systemd/system/mysql.service
      state: absent
    when:
      - item.key == 'mariadb.service'
      - item.value.state == 'running'
    with_dict: "{{ ansible_facts.services }}"

  - name: delete symbolic links
    file:
      path: /etc/systemd/system/mysqld.service
      state: absent
    when:
      - item.key == 'mariadb.service'
      - item.value.state == 'running'
    with_dict: "{{ ansible_facts.services }}"
  when:
    - database != 'mariadb'
