---
- name: get Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose

- name: chmod docker-compose
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
