---
- name: removed older docker
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: stat docker-ce.repo
  stat:
    path: '/etc/yum.repos.d/docker-ce.repo'
  register: is_docker_ce_repo

- name: yum-config add docker-ce repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: not is_docker_ce_repo.stat.exists

- name: docker installed
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: docker started and enabled
  service:
    name: docker
    state: restarted
    enabled: yes
