---

- name: mkdir ssl
  file: path=/etc/pki/tls/vap state=directory owner=root

- name: generate a key
  command: openssl genrsa -out /etc/pki/tls/vap/vap.key 2048

- name: generate a csr
  command: openssl req -new -key /etc/pki/tls/vap/vap.key -subj "/C=JP/ST=Tokyo/L=Minato-ku/O=vap/OU=vap/CN={{ HOSTNAME }} CA" -out /etc/pki/tls/vap/vap.csr

- name: generate a crt
  command: openssl x509 -days 365 -req -signkey /etc/pki/tls/vap/vap.key -in /etc/pki/tls/vap/vap.csr -out /etc/pki/tls/vap/vap.crt
