---
- name: stat /tmp/openssl-1.0.2k
  stat:
    path: /tmp/openssl-1.0.2k
  register: is_tmp_openssl_dir

- name: include task
  include: install.yml
  when: not is_tmp_openssl_dir.stat.exists

- name: include task
  include: ca.yml

- name: include task
  include: server.yml
