---
- name: stat /tmp/openssl-1.0.2k
  stat:
    path: /tmp/openssl-1.0.2k
  register: is_tmp_openssl_dir

- name: include task
  include: install.yml
  when: not is_tmp_openssl_dir.stat.exists

- name: stat privkey.pem
  stat:
    path: /etc/pki/tls/vap/privkey.pem
  register: is_vap_privkey

- block:
  - name: mkdir ssl
    file:
      path: /etc/pki/tls/vap
      state: directory
      owner: root

  - name: generate a key
    command: openssl genrsa -out /etc/pki/tls/vap/privkey.pem 2048

  - name: generate a csr
    command: openssl req -new -sha256 -key /etc/pki/tls/vap/privkey.pem -subj "/C=JP/ST=Tokyo/L=Minato-ku/O=vap/OU=vap/CN={{ HOSTNAME }} CA" -out /etc/pki/tls/vap/csr.pem

  - name: generate a crt (self Certification Authority)
    command: openssl x509 -req -sha256 -in /etc/pki/tls/vap/csr.pem -signkey /etc/pki/tls/vap/privkey.pem -out /etc/pki/tls/vap/crt.pem -days 3650

  when: not is_vap_privkey.stat.exists
