---
- name: build environment
  package: name={{ item }} state=latest
  with_items:
    - patch
    - libxml2-devel
    - bison
    - bison-devel
    - openssl-devel
    - curl
    - curl-devel
    - libjpeg-devel
    - libpng-devel
    - libmcrypt-devel
    - readline-devel
    - libtidy-devel
    - libxslt-devel
    - re2c
