---
- name: git checkout phpenv
  git:
    repo: https://github.com/madumlao/phpenv.git
    dest: "{{ home_dir }}/.phpenv"
    force: yes
    recursive: no
  become: yes
  become_user: vagrant

- name: edit PATH phpenv on .bash_profile
  lineinfile:
    dest: "{{ home_dir }}/.bash_profile"
    line: "export PATH=$HOME/.phpenv/bin:$PATH"

- name: edit PATH phpenv on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "export PATH=$HOME/.phpenv/bin:$PATH"

- name: edit phpenv init on .bash_profile
  lineinfile:
    dest: "{{ home_dir }}/.bash_profile"
    line: "eval \"$(phpenv init -)\""

- name: edit phpenv init on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "eval \"$(phpenv init -)\""

- name: git checkout php-build
  git:
    repo: https://github.com/php-build/php-build.git
    dest: "{{ home_dir }}/.phpenv/plugins/php-build"
    force: yes
  become: yes
  become_user: vagrant

- name: git checkout phpenv-composer
  git:
    repo: https://github.com/ngyuki/phpenv-composer.git
    dest: "{{ home_dir }}/.phpenv/plugins/phpenv-composer"
    force: yes
  become: yes
  become_user: vagrant

- name: git checkout phpenv-apache-version
  git:
    repo: https://github.com/thingsym/phpenv-apache-version.git
    dest: "{{ home_dir }}/.phpenv/plugins/phpenv-apache-version"
    force: yes
  become: yes
  become_user: vagrant
  when: server == 'apache'

- include: build-env.yml

- name: stat custom php-build.default_configure_options.j2
  stat:
    path: /vagrant/config/php-build.default_configure_options.j2
  register: is_custom_default_configure_options

- name: custom default_configure_options changed
  template:
    src: /vagrant/config/php-build.default_configure_options.j2
    dest: "{{ phpenv_dir }}.phpenv/plugins/php-build/share/php-build/default_configure_options"
  when: is_custom_default_configure_options.stat.exists

- name: set default_configure_options
  template:
    src: php-build.default_configure_options.j2
    dest: "{{ home_dir }}/.phpenv/plugins/php-build/share/php-build/default_configure_options"
  when: not is_custom_default_configure_options.stat.exists

- name: stat php_path
  stat:
    path: "{{ home_dir }}/.phpenv/versions/{{ php_version | default(7.0.7) }}"
  register: is_php_path

- name: php installed via phpenv.sh
  command: sudo -u vagrant -i -- /vagrant/command/phpenv.sh {{ php_version | default(7.0.7) }}
  when: not is_php_path.stat.exists

- include: php-fpm.yml
  when: fastcgi == "php-fpm"

- name: create symbolic link
  file:
    src: "{{ home_dir }}/.phpenv/shims/php"
    dest: /usr/bin/php
    state: link
    force: yes

- name: packagist.jp repository added
  command: sudo -u vagrant -i -- {{ home_dir }}/.phpenv/shims/composer config -g repos.packagist composer https://packagist.jp

- name: prestissimo installed
  command: sudo -u vagrant -i -- {{ home_dir }}/.phpenv/shims/composer global require 'hirak/prestissimo=^0.3'
