name: Ansible lint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python: [ 2.7, 3.6, 3.7, 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python v${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Ansible and Ansible Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run checking syntax
        run: ansible-playbook --syntax-check -i hosts/local site.yml

      - name: Run lint
        run: ansible-lint site.yml
